export default [
    {   id: 1,
        title:"Iron Many",
        year: 2008,
        info:"Tony Stark, billionaire and weapons designer, gives up his life of arms dealing in favor of saving the world when he's nearly fatally injured by terrorists. He builds a suit of powered armor, takes the name Iron Man, and thwarts his power-hungry business rival.",

    },

    {   id: 2,
        title:"The Incredible Hulk",
        year:2008,
        info:"",
    },

    {   id: 3,
        title:"Iron Man 2",
        year:2010,
        info:"",
    },

    {   id: 4,
        title:"Thor",
        year:2011,
        info:"",
    },

    {   id: 5,
        title:"Captain America: The First Avenger",
        year:2011,
        info:"",
    },

    {   id: 6,
        title:"Marvel's The Avengers",
        year:2012,
        info:"",
    },

    {   id: 7,
        title:"Iron Man 3",
        year:2013,
        info:"",
    },

    {   id: 8,
        title:"Thor: The Dark World",
        year:2013,
        info:"",
    },

    {   id: 9,
        title:"Captain America: The Winter Soldier",
        year:2014,
        info:"",
    },

    {   id: 10,
        title:"Guardians of the Galaxy",
        year:2014,
        info:"",
    },

    {   id: 11,
        title:"Avengers: Age of Ultron",
        year:2015,
        info:"",
    },

    {   id: 12,
        title:"Ant-Man",
        year:2015,
        info:"",
    },

    {   id: 13,
        title:"Captain America: Civil",
        year:2016,
        info:"",
    },

    {   id: 14,
        title:"Doctor Strange",
        year:2016,
        info:"",
    },

    {   id: 15,
        title:"Guardians of the Galaxy Vol.2",
        year:2017,
        info:"",
    },

    {   id: 16,
        title:"Spider-Man: Homecoming",
        year:2017,
        info:"",
    },

    {   id: 17,
        title:"Thor: Ragnarok",
        year:2017,
        info:"",
    },

    {   id: 18,
        title:"Black Panther",
        year:2018,
        info:"",
    },

    {   id: 19,
        title:"Avengers: Infinity War",
        year:2018,
        info:"",
    },

    {   id: 20,
        title:"Ant-Man and the Wasp",
        year:2018,
        info:"",
    },

    {   id: 21,
        title:"Captain Marvel",
        year:2019,
        info:"",
    },

    {   id: 22,
        title:"Avengers: Endgame",
        year:2019,
        info:"",
    },

    {   id: 23,
        title:"Spider-Man: Far From Home",
        year:2019,
        info:"",
    },

    {   id: 24,
        title:"Black Widow",
        year:2021,
        info:"",
    },

    {   id: 25,
        title:"Shang-Chi and the Legend of the Ten Rings",
        year:2021,
        info:"",
    },

    {   id: 26,
        title:"Eternals",
        year:2021,
        info:"",
    },

    {   id: 27,
        title:"Spider-Man: No Way Home",
        year:2021,
        info:"",
    },

    {   id: 28,
        title:"Doctor Strange in the Multiverse of Madness",
        year:2022,
        info:"",
    },

    {   id: 29,
        title:"Thor: Love and Thunder",
        year:2022,
        info:"",
    },

    {   id: 30,
        title:"Black Panther: Wakanda Forever",
        year:2022,
        info:"",
    }


];